FROM node:14 AS builder

WORKDIR /app

COPY package\*.json ./

RUN npm install

COPY .env .env

COPY . .

RUN npm run build

FROM nginx:1.16.0-alpine

COPY --from=builder ./app /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx/nginx.conf /etc/nginx/conf.d

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
