export const brazilStates = [
  { nome: 'ACRE', sigla: 'AC' },
  { nome: 'ALAGOAS', sigla: 'AL' },
  { nome: 'AMAPÁ', sigla: 'AP' },
  { nome: 'AMAZONAS', sigla: 'AM' },
  { nome: 'BAHIA', sigla: 'BA' },
  { nome: 'CEARÁ', sigla: 'CE' },
  { nome: 'DISTRITO FEDERAL', sigla: 'DF' },
  { nome: 'ESPÍRITO SANTO', sigla: 'ES' },
  { nome: 'GOIÁS', sigla: 'GO' },
  { nome: 'MARANHÃO', sigla: 'MA' },
  { nome: 'MATO GROSSO', sigla: 'MT' },
  { nome: 'MATO GROSSO DO SUL', sigla: 'MS' },
  { nome: 'MINAS GERAIS', sigla: 'MG' },
  { nome: 'PARÁ', sigla: 'PA' },
  { nome: 'PARAÍBA', sigla: 'PB' },
  { nome: 'PARANÁ', sigla: 'PR' },
  { nome: 'PERNAMBUCO', sigla: 'PE' },
  { nome: 'PIAUÍ', sigla: 'PI' },
  { nome: 'RIO DE JANEIRO', sigla: 'RJ' },
  { nome: 'RIO GRANDE DO NORTE', sigla: 'RN' },
  { nome: 'RIO GRANDE DO SUL', sigla: 'RS' },
  { nome: 'RONDÔNIA', sigla: 'RO' },
  { nome: 'RORAIMA', sigla: 'RR' },
  { nome: 'SANTA CATARINA', sigla: 'SC' },
  { nome: 'SÃO PAULO', sigla: 'SP' },
  { nome: 'SERGIPE', sigla: 'SE' },
  { nome: 'TOCANTINS', sigla: 'TO' }
];
